"""
Inside of the "Extraction Plan" card: the plan file (extract_pipeline.yaml) the receiver opens.

The page reads the plan; this widget only shows it and sends what the user dropped.
The final files have their own card (final_files_panel.py).
"""
from PyQt6.QtCore import Qt, pyqtSignal
from PyQt6.QtWidgets import QFrame, QLabel, QVBoxLayout

from src.gui.components.gui_utils import truncate_text_middle
from src.gui.components.widgets.file_info_bar import FileInfoBar
from src.gui.components.widgets.files_drop import FileDropWidget
from src.path import svg_path

NAME_LIMIT = 32  # long pipeline names are cut in the middle (the tooltip keeps the full name)


class ExtractPlanPanel(QFrame):
    plan_selected = pyqtSignal(str)          # path of the extract_pipeline.yaml the user chose
    change_plan_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.build_ui()
        self.clear_plan()

    def build_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 4, 16, 16)
        layout.setSpacing(10)

        description = QLabel("Load the steps generated by Embed → Run Pipeline.")
        description.setObjectName("hintLabel")
        description.setWordWrap(True)
        layout.addWidget(description)

        # Plan file: a drop zone before a plan is read, then its summary with Change
        self.plan_drop = FileDropWidget(
            "Drop extraction plan file here or click to browse",
            "Supported: .yaml, .yml",
            icon_path=str(svg_path("file-import.svg")),
            allowed_extensions=[".yaml", ".yml"],
            show_preview=False,
        )
        self.plan_drop.setToolTip("Open extract_pipeline.yaml generated by Embed → Run Pipeline.")
        self.plan_drop.main_label.setWordWrap(True)
        self.plan_drop.sub_label.setWordWrap(True)
        self.plan_drop.drop_layout.setAlignment(self.plan_drop.main_label, Qt.AlignmentFlag.AlignVCenter)
        self.plan_drop.drop_layout.setAlignment(self.plan_drop.sub_label, Qt.AlignmentFlag.AlignVCenter)
        self.plan_drop.setFixedHeight(110)
        self.plan_drop.file_selected.connect(lambda path: path and self.plan_selected.emit(path))
        self.plan_bar = FileInfoBar()
        self.plan_bar.change_file_button.setText("Change")
        self.plan_bar.change_file_requested.connect(self.on_change_plan)
        layout.addWidget(self.plan_drop)
        layout.addWidget(self.plan_bar)

    def on_change_plan(self) -> None:
        """Change = take the plan out: back to the drop zone (the page clears the steps and the files)."""
        self.plan_drop.clear_all()  # so choosing the same file again is still noticed
        self.plan_bar.hide()
        self.plan_drop.show()
        self.change_plan_requested.emit()

    # --- What the page shows ---
    def show_plan(self, file_path: str, name: str, detail: str) -> None:
        """name: the pipeline name (or the file name) · detail: e.g. 'YAML · 4 steps · 3 stego files'"""
        self.plan_bar.update_info(file_path, truncate_text_middle(name, NAME_LIMIT), detail, [],
                                  icon_path=str(svg_path("file-text.svg")))
        self.plan_bar.file_name.setToolTip(name)
        self.plan_drop.clear_all()
        self.plan_drop.hide()
        self.plan_bar.show()

    def clear_plan(self) -> None:
        self.plan_bar.hide()
        self.plan_drop.show()
